Some fixes

diff --git a/Dots-WM/Openbox-OldMC/bashrc b/Dots-WM/Openbox-OldMC/bashrc
--- a/Dots-WM/Openbox-OldMC/bashrc
+++ b/Dots-WM/Openbox-OldMC/bashrc
@@ -1,6 +1,5 @@
 ## VoidLinux
 
-
 #grub update
 # alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
 
@@ -36,13 +35,11 @@ alias microcode='grep . /sys/devices/system/cpu/vulnerabilities/*'
 #remove
 alias rmgitcache="rm -r ~/.cache/git"
 
-
 #hardware info --short
 alias hw="hwinfo --short"
 
 #add new fonts
 alias update-fc='sudo fc-cache -fv'
-
 
 # Play audio files in current dir by type - If you have DeadBeef
 alias playwav='deadbeef *.wav'
@@ -66,7 +63,6 @@ alias yta-vorbis="yt-dlp --extract-audio --audio-format vorbis "
 alias yta-wav="yt-dlp --extract-audio --audio-format wav "
 alias ytv-best="yt-dlp -f bestvideo+bestaudio "
 alias ytv-best-mp4="yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 "
-
 
 # switch between shells
 # I do not recommend switching default SHELL from bash.
@@ -93,18 +89,17 @@ alias rg="rg --sort path"
 [[ $- != *i* ]] && return
 
 ### PATH
-if [ -d "$HOME/.bin" ] ;
-  then PATH="$HOME/.bin:$PATH"
+if [ -d "$HOME/.bin" ]; then
+  PATH="$HOME/.bin:$PATH"
 fi
 
-if [ -d "$HOME/.local/bin" ] ;
-  then PATH="$HOME/.local/bin:$PATH"
+if [ -d "$HOME/.local/bin" ]; then
+  PATH="$HOME/.local/bin:$PATH"
 fi
 
-if [ -d "$HOME/Applications" ] ;
-  then PATH="$HOME/Applications:$PATH"
+if [ -d "$HOME/Applications" ]; then
+  PATH="$HOME/Applications:$PATH"
 fi
-
 
 # Make nano the default editor
 
@@ -123,12 +118,11 @@ bind "set completion-ignore-case on"
 export XDG_RUNTIME_DIR=$PATH:~/.cache/xdgr
 
 ### EXPORT
-export TERM="xterm-256color"                      # getting proper colors
-export HISTCONTROL=ignoredups:erasedups           # no duplicate entries
+export TERM="xterm-256color"            # getting proper colors
+export HISTCONTROL=ignoredups:erasedups # no duplicate entries
 # export ALTERNATE_EDITOR=""                        # setting for emacsclient
 # export EDITOR="emacsclient -t -a ''"              # $EDITOR use Emacs in terminal
 # export VISUAL="emacsclient -c -a emacs"           # $VISUAL use Emacs in GUI mode
-
 
 ### "bat" as manpager
 export MANPAGER="sh -c 'col -bx | bat -l man -p'"
@@ -151,7 +145,6 @@ alias l.='exa -a | egrep "^\."'
 alias cd..='cd ..'
 alias pdw="pwd"
 alias update='doas vpm sync && doas vpm update '
-
 
 #alias ls='ls --color=auto'
 alias desligar="doas shutdown -h now"
@@ -176,8 +169,8 @@ alias rm='rm -i'
 alias give-me-qwerty-us="doas localectl set-x11-keymap us"
 
 # adding flags
-alias df='df -Th'                          # human-readable sizes
-alias free='free -m'                      # show sizes in MB
+alias df='df -Th'    # human-readable sizes
+alias free='free -m' # show sizes in MB
 # alias lynx='lynx -cfg=~/.lynx/lynx.cfg -lss=~/.lynx/lynx.lss -vikeys'  # Vim broser
 # alias vifm='./.config/vifm/scripts/vifmrun'
 alias ncmpcpp='ncmpcpp ncmpcpp_directory=$HOME/.config/ncmpcpp/'
@@ -202,7 +195,6 @@ alias comused="history | awk '{print $2}' | sort | uniq -c | sort -nr | head -5"
 
 #####       Nano        #####
 
-
 #nano for important configuration files
 #know what you do in these files
 # alias nlxdm="doas $EDITOR /etc/lxdm/lxdm.conf"
@@ -220,10 +212,10 @@ alias nz="$EDITOR ~/.zshrc"
 #####              #####                ######
 
 ## Settings for umask
-if (( EUID == 0 )); then
-      umask 002
+if ((EUID == 0)); then
+  umask 002
 else
-      umask 022
+  umask 022
 fi
 
 ## global aliases (for those who like them) ##
@@ -251,7 +243,7 @@ alias top10='print -l ${(o)history%% *} | uniq -c | sort -nr | head -n 10'
 
 ## Memory overview
 memusage() {
-   ps aux | awk '{if (NR > 1) print $5;
+  ps aux | awk '{if (NR > 1) print $5;
                   if (NR > 2) print "+"}
                   END { print "p" }' | dc
 }
@@ -281,7 +273,7 @@ export MANWIDTH=${MANWIDTH:-80}
 
 # set a fancy prompt (non-color, unless we know we "want" color)
 # case "$TERM" in
-  # xterm-color) color_prompt=yes;;
+# xterm-color) color_prompt=yes;;
 # esac
 
 # uncomment for a colored prompt, if the terminal has the capability; turned
@@ -341,37 +333,47 @@ export MANWIDTH=${MANWIDTH:-80}
 # -R: show ANSI colors correctly; -i: case insensitive search
 LESS="-R -i"
 
-
 # enable programmable completion features (you don't need to enable
 # this, if it's already enabled in /etc/bash.bashrc and /etc/profile
 # sources /etc/bash.bashrc).
 if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
-    . /etc/bash_completion
+  . /etc/bash_completion
 fi
 
+# enable bash completion in interactive shells
+if ! shopt -oq posix; then
+  if [ -f /usr/share/bash-completion/bash_completion ]; then
+    . /usr/share/bash-completion/bash_completion
+  elif [ -f /etc/bash_completion ]; then
+    . /etc/bash_completion
+  fi
+fi
+
+bind 'set show-all-if-ambiguous on'
+bind 'TAB:menu-complete'
+
 # Add sbin directories to PATH.  This is useful on systems that have sudo
-echo $PATH | grep -Eq "(^|:)/sbin(:|)"     || PATH=$PATH:/sbin
+echo $PATH | grep -Eq "(^|:)/sbin(:|)" || PATH=$PATH:/sbin
 echo $PATH | grep -Eq "(^|:)/usr/sbin(:|)" || PATH=$PATH:/usr/sbin
 
 ### CHANGE TITLE OF TERMINALS
 case ${TERM} in
-  xterm*|rxvt*|Eterm*|aterm|kitty|kterm|gnome*|alacritty|st|konsole*)
-    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\007"'
-        ;;
-  screen*)
-    PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\033\\"'
-    ;;
+xterm* | rxvt* | Eterm* | aterm | kitty | kterm | gnome* | alacritty | st | konsole*)
+  PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\007"'
+  ;;
+screen*)
+  PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\033\\"'
+  ;;
 esac
 
 ### SHOPT
-shopt -s autocd # change to named directory
+shopt -s autocd  # change to named directory
 shopt -s cdspell # autocorrects cd misspellings
 shopt -s cmdhist # save multi-line commands in history as single line
 shopt -s dotglob
-shopt -s histappend # do not overwrite history
+shopt -s histappend     # do not overwrite history
 shopt -s expand_aliases # expand aliases
-shopt -s checkwinsize # checks term size when bash regains control
-
+shopt -s checkwinsize   # checks term size when bash regains control
 
 ### PROMPT
 # This is commented out if using starship prompt
@@ -383,37 +385,35 @@ export PATH="$HOME/scripts/fontpreview:$PATH"
 
 # If not running interactively, don't do anything
 case $- in
-  *i*) ;;
-    *) return;;
+*i*) ;;
+*) return ;;
 esac
 
 ### ARCHIVE EXTRACTION
 # usage: ex <file>
-ex ()
-{
-  if [ -f "$1" ] ; then
+ex() {
+  if [ -f "$1" ]; then
     case $1 in
-      *.tar.bz2)   tar xjf $1   ;;
-      *.tar.gz)    tar xzf $1   ;;
-      *.bz2)       bunzip2 $1   ;;
-      *.rar)       unrar x $1   ;;
-      *.gz)        gunzip $1    ;;
-      *.tar)       tar xf $1    ;;
-      *.tbz2)      tar xjf $1   ;;
-      *.tgz)       tar xzf $1   ;;
-      *.zip)       unzip $1     ;;
-      *.Z)         uncompress $1;;
-      *.7z)        7z x $1      ;;
-      *.deb)       ar x $1      ;;
-      *.tar.xz)    tar xf $1    ;;
-      *.tar.zst)   unzstd $1    ;;
-      *)           echo "'$1' cannot be extracted via ex()" ;;
+    *.tar.bz2) tar xjf $1 ;;
+    *.tar.gz) tar xzf $1 ;;
+    *.bz2) bunzip2 $1 ;;
+    *.rar) unrar x $1 ;;
+    *.gz) gunzip $1 ;;
+    *.tar) tar xf $1 ;;
+    *.tbz2) tar xjf $1 ;;
+    *.tgz) tar xzf $1 ;;
+    *.zip) unzip $1 ;;
+    *.Z) uncompress $1 ;;
+    *.7z) 7z x $1 ;;
+    *.deb) ar x $1 ;;
+    *.tar.xz) tar xf $1 ;;
+    *.tar.zst) unzstd $1 ;;
+    *) echo "'$1' cannot be extracted via ex()" ;;
     esac
   else
     echo "'$1' is not a valid file"
   fi
 }
-
 
 ### ALIASES ###
 
@@ -421,7 +421,7 @@ ex ()
 # alias doas="doas --"
 
 # navigation
-up () {
+up() {
   local d=""
   local limit="$1"
 
@@ -430,13 +430,13 @@ up () {
     limit=1
   fi
 
-  for ((i=1;i<=limit;i++)); do
+  for ((i = 1; i <= limit; i++)); do
     d="../$d"
   done
 
   # perform cd. Show error if cd fails
   if ! cd "$d"; then
-    echo "Couldn't go up $limit dirs.";
+    echo "Couldn't go up $limit dirs."
   fi
 }
 
@@ -459,10 +459,9 @@ alias commit='git commit -m'
 alias fetch='git fetch'
 alias pull='git pull origin'
 alias push='git push origin'
-alias stat='git status'  # 'status' is protected name so using 'stat' instead
+alias stat='git status' # 'status' is protected name so using 'stat' instead
 alias tag='git tag'
 alias newtag='git tag -a'
-
 
 ##### Xdeb Configs (VoidLinux) ####
 
@@ -478,13 +477,11 @@ colorscript random
 
 ### BASH INSULTER (works in zsh though) ###
 if [ -f /etc/bash.command-not-found ]; then
-    . /etc/bash.command-not-found
+  . /etc/bash.command-not-found
 fi
 
 ### SETTING THE STARSHIP PROMPT ###
 eval "$(starship init bash)"
-
-
 
 # xrandr
 # LVDS-1  1920x1200
